trigger:
  branches:
    include:
      - main

variables:
- group: KeyVault-Secrets
- group: notifications
- group: targetgroupid
- name: SCRIPT_FOLDER
  value: 'intune-scripts'
- name: TEST_FOLDER
  value: 'pester-tests'
- name: TEST_RESULTS
  value: 'Test-Pester.xml'

pool:
  name: Default

stages:
- stage: DiscoverFiles
  displayName: Discover Script & Test Files
  jobs:
  - template: templates/discover-files.yml

- stage: PesterTests
  dependsOn: DiscoverFiles
  variables:
    TEST_PATHS: $[ stageDependencies.DiscoverFiles.DiscoverFiles.outputs['SetVars.TEST_PATHS'] ]
  jobs:
  - template: templates/test-pester.yml

- stage: PSScriptAnalyzer
  dependsOn: DiscoverFiles
  variables:
    SCRIPT_PATHS: $[ stageDependencies.DiscoverFiles.DiscoverFiles.outputs['SetVars.SCRIPT_PATHS'] ]
  jobs:
  - template: templates/lint-psscriptanalyzer.yml

- stage: DeployToIntune
  dependsOn: 
    - PesterTests
    - PSScriptAnalyzer
  condition: and(succeeded('PesterTests'), succeeded('PSScriptAnalyzer'))
  jobs:
  - template: templates/deploy-intune.yml

- stage: AssignPolicies
  dependsOn: DeployToIntune
  condition: succeeded('DeployToIntune')
  jobs:
  - job: ParseAssignments
    displayName: Parse Script Assignments
    steps:
      - download: current
        artifact: ScriptAssignments

      - task: PowerShell@2
        name: SetAssignments
        inputs:
          targetType: 'inline'
          pwsh: true
          script: |
            $jsonPath = "$(Pipeline.Workspace)/ScriptAssignments/script-assignments.json"
            $json = Get-Content -Raw -Path $jsonPath | ConvertFrom-Json
            $jsonText = $json | ConvertTo-Json -Depth 5 -Compress
            $encoded = [Convert]::ToBase64String([System.Text.Encoding]::UTF8.GetBytes($jsonText))
            Write-Host "##vso[task.setvariable variable=ScriptAssignmentsEncoded;isOutput=true]$encoded"

  - template: templates/assign-policy.yml
    parameters:
      tenantId: $(TenantId)
      clientId: $(ClientId)
      clientSecret: $(clientsecret4053)
      targetGroupId: $(TargetGroupId)
      scriptAssignments: $[ dependencies.ParseAssignments.outputs['SetAssignments.ScriptAssignmentsJson'] ]


- stage: NotifyMsTeam-Slack
  displayName: Notify Slack & Teams
  dependsOn:
   #- AssignPolicies
    - DeployToIntune
  condition: always()
  jobs:
  - template: templates/notify-slack.yml
    parameters:
      webhookUrl: $(SLACK_WEBHOOK_URL)
      pipelineName: $(Build.DefinitionName)
      status: $(Agent.JobStatus)

  - template: templates/notify-teams.yml
    parameters:
      webhookUrl: $(MSTEAM_WEBHOOK_URL)
      pipelineName: $(Build.DefinitionName)
      status: $(Agent.JobStatus)

